### ISSUE TITLE
Unable to setup server

### ISSUE THREAD

**Issue by ChaiBapchya** [dirkweissenborn/ctakes-server#7]
Followed all the commands for cloning repos and setting up server,
Command
```
java -Dctakes.umlsuser='user' -Dctakes.umlspw='mypass' -Xmx3g -cp target/ctakes-server-0.1.jar:resources/ de.dfki.lt.ctakes.Server localhost 9999 desc/ctakes-clinical-pipeline/desc/analysis_engine/AggregatePlaintextFastUMLSProcessor.xml
```

Error - 
```
Exception in thread "main" org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/Users/chaitanyabapat/8903/ctakes-server/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
```

Error-trace - 
```
java -Dctakes.umlsuser='user' -Dctakes.umlspw='mypass' -Xmx3g -cp target/ctakes-server-0.1.jar:resources/ de.dfki.lt.ctakes.Server localhost 9999 desc/ctakes-clinical-pipeline/desc/analysis_engine/AggregatePlaintextFastUMLSProcessor.xml
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressAppender] additivity to [false].
log4j: Level value for ProgressAppender is  [INFO].
log4j: ProgressAppender level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m].
log4j: Adding appender named [noEolAppender] to category [ProgressAppender].
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressDone] additivity to [false].
log4j: Level value for ProgressDone is  [INFO].
log4j: ProgressDone level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m%n].
log4j: Adding appender named [eolAppender] to category [ProgressDone].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{dd MMM yyyy HH:mm:ss} %5p %c{1} - %m%n].
log4j: Adding appender named [consoleAppender] to category [root].
11 Nov 2017 17:05:47  INFO LvgCmdApiResourceImpl - Loading NLM Norm and Lvg with config file = /Users/chaitanyabapat/8903/apache-ctakes-4.0.0/resources/org/apache/ctakes/lvg/data/config/lvg.properties
11 Nov 2017 17:05:47  INFO LvgCmdApiResourceImpl -   config file absolute path = /Users/chaitanyabapat/8903/apache-ctakes-4.0.0/resources/org/apache/ctakes/lvg/data/config/lvg.properties
11 Nov 2017 17:05:47  INFO LvgCmdApiResourceImpl - cwd = /Users/chaitanyabapat/8903/ctakes-server
11 Nov 2017 17:05:47  INFO LvgCmdApiResourceImpl - cd /Users/chaitanyabapat/8903/apache-ctakes-4.0.0/resources/org/apache/ctakes/lvg/
java.sql.SQLException: error in script file line: 1 Unexpected token UNIQUE, requires COLLATION in statement [SET DATABASE UNIQUE]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
	at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source)
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbcDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at gov.nih.nlm.nls.lvg.Db.DbBase.OpenConnection(DbBase.java:40)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.InitDbAndTrie(LvgCmdApi.java:1479)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.Init(LvgCmdApi.java:1432)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.<init>(LvgCmdApi.java:86)
	at org.apache.ctakes.lvg.resource.LvgCmdApiResourceImpl.load(LvgCmdApiResourceImpl.java:89)
	at org.apache.uima.resource.impl.ResourceManager_impl.registerResource(ResourceManager_impl.java:603)
	at org.apache.uima.resource.impl.ResourceManager_impl.initializeExternalResources(ResourceManager_impl.java:442)
	at org.apache.uima.resource.Resource_ImplBase.initialize(Resource_ImplBase.java:153)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.initialize(AnalysisEngineImplBase.java:157)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:123)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:354)
	at de.dfki.lt.ctakes.Server$.main(Server.scala:35)
	at de.dfki.lt.ctakes.Server.main(Server.scala)
java.sql.SQLException: error in script file line: 1 Unexpected token UNIQUE, requires COLLATION in statement [SET DATABASE UNIQUE]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
	at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source)
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbcDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at gov.nih.nlm.nls.lvg.Db.DbBase.OpenConnection(DbBase.java:40)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.InitDbAndTrie(LvgCmdApi.java:1479)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.Init(LvgCmdApi.java:1432)
	at gov.nih.nlm.nls.lvg.Api.LvgCmdApi.<init>(LvgCmdApi.java:86)
	at gov.nih.nlm.nls.lvg.Api.LvgLexItemApi.<init>(LvgLexItemApi.java:80)
	at org.apache.ctakes.lvg.resource.LvgCmdApiResourceImpl.load(LvgCmdApiResourceImpl.java:94)
	at org.apache.uima.resource.impl.ResourceManager_impl.registerResource(ResourceManager_impl.java:603)
	at org.apache.uima.resource.impl.ResourceManager_impl.initializeExternalResources(ResourceManager_impl.java:442)
	at org.apache.uima.resource.Resource_ImplBase.initialize(Resource_ImplBase.java:153)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.initialize(AnalysisEngineImplBase.java:157)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:123)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:354)
	at de.dfki.lt.ctakes.Server$.main(Server.scala:35)
	at de.dfki.lt.ctakes.Server.main(Server.scala)
11 Nov 2017 17:05:47  INFO LvgCmdApiResourceImpl - cd /Users/chaitanyabapat/8903/ctakes-server
11 Nov 2017 17:05:47  INFO ClearNLPDependencyParserAE - using Morphy analysis? true
Loading configuration.
Loading feature templates.
Loading lexica.
Loading model:
........................................................................................
11 Nov 2017 17:05:59  INFO Chunker - Chunker model file: org/apache/ctakes/chunker/models/chunker-model.zip
11 Nov 2017 17:06:01  INFO ContextDependentTokenizerAnnotator - Finite state machines loaded.
11 Nov 2017 17:06:01  INFO ConstituencyParser - Initializing parser...
11 Nov 2017 17:06:05  INFO ContextAnnotator - SCOPE ORDER: [1, 3]
11 Nov 2017 17:06:05  INFO NegationContextAnalyzer - initBoundaryData() called for ContextInitializer
11 Nov 2017 17:06:05  INFO DrugMentionAnnotator - Finite state machines loaded.
11 Nov 2017 17:06:06  INFO POSTagger - POS tagger model file: org/apache/ctakes/postagger/models/mayo-pos.zip
11 Nov 2017 17:06:06  INFO AbstractJCasTermAnnotator - Using dictionary lookup window type: org.apache.ctakes.typesystem.type.textspan.Sentence
11 Nov 2017 17:06:06  INFO AbstractJCasTermAnnotator - Exclusion tagset loaded: CC CD DT EX IN LS MD PDT POS PP PP$ PRP PRP$ RP TO VB VBD VBG VBN VBP VBZ WDT WP WPS WRB 
11 Nov 2017 17:06:06  INFO AbstractJCasTermAnnotator - Using minimum term text span: 3
Exception in thread "main" org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/Users/chaitanyabapat/8903/ctakes-server/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:252)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:156)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:354)
	at de.dfki.lt.ctakes.Server$.main(Server.scala:35)
	at de.dfki.lt.ctakes.Server.main(Server.scala)
Caused by: java.lang.NullPointerException
	at org.apache.ctakes.dictionary.lookup2.ae.AbstractJCasTermAnnotator.initialize(AbstractJCasTermAnnotator.java:129)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:250)
	... 15 more
```

**Comment by dirkweissenborn** [comment]
these errors are CTakes specific errors and have nothing to do with this server. the server simply converts the output CAS to json and provides a REST interface.

**Comment by ashanideepta** [comment]
I am trying to run the code on a blank new EC2 instance and I get this exact same error. @ChaiBapchya did you find a solution to this error?

**Comment by ChaiBapchya** [comment]
Umm no. I was stuck on that too.

**Comment by dermatologist** [comment]
Same here. Any solution yet?

**Comment by parthnatu** [comment]
change `<ctakes.version>` tag in `pom.xml` to 4.0.0

**Comment by humehta** [comment]
where do we change the pom.xml?
where can we find it?

**Comment by parthnatu** [comment]
It's in the root of this repository.

**Comment by sakatipomu** [comment]
any solution for this problem?

**Comment by parthnatu** [comment]
[This file is present in the root of the repository when you clone it.](https://github.com/dirkweissenborn/ctakes-server/blob/master/pom.xml) Change the version to 4.0.0

**Comment by sakatipomu** [comment]
@parthnatu, Thank you for the suggestion. But I am not using ctakes-server, I have imported ctakes developer version from ctakes website. So I do not have this pom.xml.But still facing this error.I tried changing ctakes/pom.xml also.

**Comment by parthnatu** [comment]
Can you paste the log here? Also I suggest following the instructions completely and reinstalling.

**Comment by sakatipomu** [comment]
@parthnatu , I have given UMLS username and password as VM arguments. I hope that error is solved now. But Currently I am facing another error. Please shed some light if you know about it.

11:33:31.06 - 16: org.apache.uima.tools.cvd.MainFrame.handleException(666): SEVERE: The class org.apache.ctakes.drugner.ae.DrugMentionAnnotator could not be found. (Descriptor: file:/Users/skatipomu/cTAKES/ctakes/ctakes-drug-ner/desc/analysis_engine/DrugMentionAnnotator.xml)
org.apache.uima.resource.ResourceInitializationException: The class org.apache.ctakes.drugner.ae.DrugMentionAnnotator could not be found. (Descriptor: file:/Users/skatipomu/cTAKES/ctakes/ctakes-drug-ner/desc/analysis_engine/DrugMentionAnnotator.xml)
	at org.apache.uima.resource.impl.ResourceManager_impl.loadUserClassOrThrow(ResourceManager_impl.java:874)
	at org.apache.uima.resource.Resource_ImplBase.loadUserClassOrThrow(Resource_ImplBase.java:334)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:210)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:173)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:289)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:417)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:435)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:379)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:192)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:289)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:381)
	at org.apache.uima.tools.cvd.MainFrame.setupAE(MainFrame.java:1803)
	at org.apache.uima.tools.cvd.MainFrame.loadAEDescriptor(MainFrame.java:605)
	at org.apache.uima.tools.cvd.control.AnnotatorOpenEventHandler.actionPerformed(AnnotatorOpenEventHandler.java:66)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.ctakes.drugner.ae.DrugMentionAnnotator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.uima.resource.impl.ResourceManager_impl.loadUserClass(ResourceManager_impl.java:856)
	at org.apache.uima.resource.impl.ResourceManager_impl.loadUserClassOrThrow(ResourceManager_impl.java:870)
	... 57 more

**Comment by parthnatu** [comment]
I think you should try reinstalling and raising this issue in the [ctakes repository](https://github.com/apache/ctakes).
